version: '3.4'

services:
  import:
    image: map:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PGDATAFILE}:/data.osm.pbf:ro
      - ${HOSTPGDATA}:${PGDATA}
      - /data/planetdb:/planetdb
    command: "import"
  map:
    image: map:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOSTPGDATA}:${PGDATA}
      - ${HOSTTILESDIR}:${TILESDIR}
    ports:
      - "8080:80"
    command: "run"
