version: '3'

services:
  import:
    image: map:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - openstreetmap-data:${PGDATA}
      - ${PGDATAFILE}:/data.osm.pbf
    command: "import"
  map:
    image: map:v1
    build:
      context: .
      dockerfile: Dockerfile   
    volumes:
      - openstreetmap-data:${PGDATA}
      - openstreetmap-rendered-tiles:${TILESDIR}      
    ports:
      - "8080:80"
    command: "run"      
     

volumes:
  openstreetmap-data:
    external: true
    name: ${PGVOLUME}
  openstreetmap-rendered-tiles:
    external: true
    name: ${TILESVOLUME}    
